Repository UMC-MindStone/BackEnd, pull requests merged in 2025-02, with the labels that each got.

#26 [Refactor] 임시 비밀번호 메일 멘트 수정
  src/main/java/Spring/MindStone/service/emailService/EmailService.java
Labels: refactor

#30 [Fix] 생성자 충돌 해결 및 CORS 에러 수정, 서버 재배포
  src/main/java/Spring/MindStone/config/SwaggerConfig.java
  src/main/java/Spring/MindStone/config/jwt/JwtTokenUtil.java
  src/main/java/Spring/MindStone/config/security/SecurityConfig.java
  src/main/java/Spring/MindStone/domain/diary/DailyEmotionStatistic.java
  src/main/java/Spring/MindStone/web/controller/OnboardingController.java
  src/test/java/Spring/MindStone/web/controller/AuthControllerTest.java
  src/test/java/Spring/MindStone/web/controller/OnboardingControllerTest.java
Labels: bug, CI/CD, refactor

#33 [Feat] 로그아웃, 회원탈퇴 기능 구현
  src/main/java/Spring/MindStone/apiPayload/code/status/ErrorStatus.java
  src/main/java/Spring/MindStone/config/SchedulerConfig.java
  src/main/java/Spring/MindStone/config/jwt/JwtRequestFilter.java
  src/main/java/Spring/MindStone/config/jwt/JwtTokenUtil.java
  src/main/java/Spring/MindStone/config/security/CustomUserDetailsService.java
  src/main/java/Spring/MindStone/config/security/SecurityConfig.java
  src/main/java/Spring/MindStone/domain/listener/MemberEntityListner.java
  src/main/java/Spring/MindStone/domain/member/MemberInfo.java
  src/main/java/Spring/MindStone/domain/tokenBlacklist/TokenBlackList.java
  src/main/java/Spring/MindStone/repository/memberRepository/MemberInfoRepository.java
  src/main/java/Spring/MindStone/repository/tokenBlacklistRepository/TokenBlacklistRepository.java
  src/main/java/Spring/MindStone/service/authService/AuthService.java
  src/main/java/Spring/MindStone/service/memberInfoService/MemberInfoService.java
  src/main/java/Spring/MindStone/service/tokenBlacklistService/TokenBlacklistService.java
  src/main/java/Spring/MindStone/web/controller/AuthController.java
  src/main/java/Spring/MindStone/web/controller/EmotionNoteController.java
  src/main/java/Spring/MindStone/web/controller/EmotionWayController.java
  src/main/java/Spring/MindStone/web/controller/MemberInfoController.java
  src/main/java/Spring/MindStone/web/dto/memberDto/MemberInfoRequestDTO.java
Labels: feature

#51 [Refactor] 회원가입 수정, SecurityConfig 수정
  src/main/java/Spring/MindStone/config/security/SecurityConfig.java
  src/main/java/Spring/MindStone/domain/listener/ListenerUtil.java
  src/main/java/Spring/MindStone/domain/listener/MemberEntityListner.java
  src/main/java/Spring/MindStone/service/memberInfoService/MemberInfoService.java
Labels: refactor
