Repository UMC-MindStone/BackEnd, pull requests merged in 2025-01, with the labels that each got.

#9 [Feature] 회원가입, 로그인 및 이메일 전송 구현
  build.gradle
  src/main/java/Spring/MindStone/MindStoneApplication.java
  src/main/java/Spring/MindStone/apiPayload/code/status/ErrorStatus.java
  src/main/java/Spring/MindStone/apiPayload/exception/handler/AuthHandler.java
  src/main/java/Spring/MindStone/apiPayload/exception/handler/MemberInfoHandler.java
  src/main/java/Spring/MindStone/config/jwt/JwtRequestFilter.java
  src/main/java/Spring/MindStone/config/jwt/JwtTokenUtil.java
  src/main/java/Spring/MindStone/config/security/CustomUserDetailsService.java
  src/main/java/Spring/MindStone/config/security/SecurityConfig.java
  src/main/java/Spring/MindStone/domain/MemberInterest.java
  src/main/java/Spring/MindStone/domain/diary/DailyDiary.java
  src/main/java/Spring/MindStone/domain/diary/DailyEmotionStatistic.java
  src/main/java/Spring/MindStone/domain/diary/DiaryImage.java
  src/main/java/Spring/MindStone/domain/emotion/Emotion.java
  src/main/java/Spring/MindStone/domain/emotion/EmotionNote.java
  src/main/java/Spring/MindStone/domain/enums/Role.java
  src/main/java/Spring/MindStone/domain/enums/Status.java
  src/main/java/Spring/MindStone/domain/friend/FriendList.java
  src/main/java/Spring/MindStone/domain/friend/MessageList.java
  src/main/java/Spring/MindStone/domain/habit/Habit.java
  src/main/java/Spring/MindStone/domain/habit/HabitHistory.java
  src/main/java/Spring/MindStone/domain/member/MemberInfo.java
  src/main/java/Spring/MindStone/domain/member/MemberInterest.java
  src/main/java/Spring/MindStone/domain/member/MemberProfile.java
  src/main/java/Spring/MindStone/repository/MemberInfoRepository.java
  src/main/java/Spring/MindStone/service/AuthService/AuthService.java
  src/main/java/Spring/MindStone/service/EmailService/EmailService.java
  src/main/java/Spring/MindStone/service/MemberInfoService/MemberInfoService.java
  src/main/java/Spring/MindStone/web/controller/AuthController.java
  src/main/java/Spring/MindStone/web/controller/MemberInfoController.java
  src/main/java/Spring/MindStone/web/dto/MemberInfoRequestDTO.java
  src/main/java/Spring/MindStone/web/dto/MemberInfoResponseDTO.java
  src/main/resources/application.yml
  src/test/java/Spring/MindStone/web/controller/AuthControllerTest.java
Labels: feature

#10 Feat/3
  build.gradle
  src/main/java/Spring/MindStone/apiPayload/code/status/ErrorStatus.java
  src/main/java/Spring/MindStone/config/security/CustomUserDetailsService.java
  src/main/java/Spring/MindStone/config/security/SecurityConfig.java
  src/main/java/Spring/MindStone/domain/emotion/EmotionNote.java
  src/main/java/Spring/MindStone/domain/member/MemberInterest.java
  src/main/java/Spring/MindStone/repository/DiaryRepository/DiaryRepository.java
  src/main/java/Spring/MindStone/repository/EmotionNoteRepository.java
  src/main/java/Spring/MindStone/repository/EmotionNoteRepository/EmotionNoteRepository.java
  src/main/java/Spring/MindStone/repository/MemberInfoRepository.java
  src/main/java/Spring/MindStone/service/DiaryService/DiaryCommandService.java
  src/main/java/Spring/MindStone/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/Spring/MindStone/service/DiaryService/DiaryQueryService.java
  src/main/java/Spring/MindStone/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/Spring/MindStone/service/EmailService/EmailService.java
  src/main/java/Spring/MindStone/service/EmotionNoteService/EmotionNoteQueryService.java
  src/main/java/Spring/MindStone/service/EmotionNoteService/EmotionNoteQueryServiceImpl.java
  src/main/java/Spring/MindStone/service/EmotionNoteService/EmotionNoteService.java
  src/main/java/Spring/MindStone/service/MemberInfoService/MemberInfoService.java
  src/main/java/Spring/MindStone/web/controller/DiaryRestController.java
  src/main/java/Spring/MindStone/web/dto/DiaryRequestDTO.java
  src/main/java/Spring/MindStone/web/dto/DiaryResponseDTO.java
  src/main/resources/application.yml
Labels: feature

#17 Feat : 감정 일기에 관한 api 추가
  build.gradle
  src/main/java/Spring/MindStone/apiPayload/code/status/ErrorStatus.java
  src/main/java/Spring/MindStone/config/S3Config.java
  src/main/java/Spring/MindStone/domain/diary/DailyDiary.java
  src/main/java/Spring/MindStone/domain/enums/EmotionList.java
  src/main/java/Spring/MindStone/domain/member/MemberInfo.java
  src/main/java/Spring/MindStone/repository/DiaryRepository/DiaryImageRepository.java
  src/main/java/Spring/MindStone/repository/DiaryRepository/DiaryRepository.java
  src/main/java/Spring/MindStone/service/DiaryService/DiaryCommandService.java
  src/main/java/Spring/MindStone/service/DiaryService/DiaryCommandServiceImpl.java
  src/main/java/Spring/MindStone/service/DiaryService/DiaryQueryService.java
  src/main/java/Spring/MindStone/service/DiaryService/DiaryQueryServiceImpl.java
  src/main/java/Spring/MindStone/service/FileService.java
  src/main/java/Spring/MindStone/web/controller/DiaryRestController.java
  src/main/java/Spring/MindStone/web/dto/diaryDto/DiaryCallendarDTO.java
  src/main/java/Spring/MindStone/web/dto/diaryDto/DiaryRequestDTO.java
  src/main/java/Spring/MindStone/web/dto/diaryDto/DiarySaveDTO.java
  src/main/java/Spring/MindStone/web/dto/diaryDto/DiaryUpdateDTO.java
  src/main/java/Spring/MindStone/web/dto/diaryDto/SimpleDiaryDTO.java
Labels: feature

#18 [Feature] 습관 추가, 수정, 조회 기능 개발
  src/main/java/Spring/MindStone/apiPayload/exception/handler/HabitHandler.java
  src/main/java/Spring/MindStone/config/security/CustomUserDetailsService.java
  src/main/java/Spring/MindStone/config/security/SecurityConfig.java
  src/main/java/Spring/MindStone/domain/enums/HabitColor.java
  src/main/java/Spring/MindStone/domain/habit/Habit.java
  src/main/java/Spring/MindStone/repository/habitRepository/HabitRepository.java
  src/main/java/Spring/MindStone/repository/memberRepository/MemberInfoRepository.java
  src/main/java/Spring/MindStone/service/AuthService/AuthService.java
  src/main/java/Spring/MindStone/service/EmailService/EmailService.java
  src/main/java/Spring/MindStone/service/MemberInfoService/MemberInfoService.java
  src/main/java/Spring/MindStone/service/habitService/HabitService.java
  src/main/java/Spring/MindStone/web/controller/AuthController.java
  src/main/java/Spring/MindStone/web/controller/HabitController.java
  src/main/java/Spring/MindStone/web/controller/MemberInfoController.java
  src/main/java/Spring/MindStone/web/dto/habitDto/HabitRequestDto.java
  src/main/java/Spring/MindStone/web/dto/habitDto/HabitResponseDto.java
  src/main/java/Spring/MindStone/web/dto/memberDto/MemberInfoRequestDTO.java
  src/main/java/Spring/MindStone/web/dto/memberDto/MemberInfoResponseDTO.java
  src/test/java/Spring/MindStone/web/controller/AuthControllerTest.java
Labels: feature

#20 [Refactor] 패키지 이름 수정
  src/main/java/Spring/MindStone/config/jwt/JwtTokenUtil.java
  src/main/java/Spring/MindStone/repository/diaryRepository/DiaryImageRepository.java
  src/main/java/Spring/MindStone/repository/diaryRepository/DiaryRepository.java
  src/main/java/Spring/MindStone/repository/emotionNoteRepository/EmotionNoteRepository.java
  src/main/java/Spring/MindStone/service/FileService.java
  src/main/java/Spring/MindStone/service/authService/AuthService.java
  src/main/java/Spring/MindStone/service/diaryService/DiaryCommandService.java
  src/main/java/Spring/MindStone/service/diaryService/DiaryCommandServiceImpl.java
  src/main/java/Spring/MindStone/service/diaryService/DiaryQueryService.java
  src/main/java/Spring/MindStone/service/diaryService/DiaryQueryServiceImpl.java
  src/main/java/Spring/MindStone/service/emailService/EmailService.java
  src/main/java/Spring/MindStone/service/emotionNoteService/EmotionNoteQueryService.java
  src/main/java/Spring/MindStone/service/emotionNoteService/EmotionNoteQueryServiceImpl.java
  src/main/java/Spring/MindStone/service/memberInfoService/MemberInfoService.java
  src/main/java/Spring/MindStone/web/controller/AuthController.java
  src/main/java/Spring/MindStone/web/controller/DiaryRestController.java
  src/main/java/Spring/MindStone/web/controller/MemberInfoController.java
Labels: refactor

#21 [Feature] 온보딩 기능 구현
  build.gradle
  gradlew
  src/main/java/Spring/MindStone/domain/member/MemberInfo.java
  src/main/java/Spring/MindStone/domain/member/MemberInterest.java
  src/main/java/Spring/MindStone/repository/memberRepository/MemberInfoRepository.java
  src/main/java/Spring/MindStone/service/habitService/HabitService.java
  src/main/java/Spring/MindStone/service/onboardingService/OnboardingService.java
  src/main/java/Spring/MindStone/web/controller/OnboardingController.java
  src/main/java/Spring/MindStone/web/dto/onboardingDto/OnboardingRequestDto.java
  src/main/java/Spring/MindStone/web/dto/onboardingDto/OnboardingResponseDto.java
  src/main/resources/application.yml
  src/test/java/Spring/MindStone/web/controller/OnboardingControllerTest.java
Labels: feature

#24 Docs: AWS 배포 관련 rds 구성 변경
  src/main/resources/application.yml
Labels: documentation, CI/CD
